# --------------------------------------------------------------------------------------------------
# SPDX-License-Identifier: Apache-2.0
# --------------------------------------------------------------------------------------------------
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/internal.cmake")

function(_besa_git_value OUTPUT_VARIABLE)
  cmake_parse_arguments(ARG "" "COMMAND;FALLBACK" "" ${ARGN})
  find_program(_git git)
  if(NOT _git)
    set("${OUTPUT_VARIABLE}" "${ARG_FALLBACK}" PARENT_SCOPE)
    return()
  endif()
  separate_arguments(_command UNIX_COMMAND "${ARG_COMMAND}")
  execute_process(
    COMMAND "${_git}" ${_command}
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    RESULT_VARIABLE _result
    OUTPUT_VARIABLE _value
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  if(NOT _result EQUAL 0 OR "${_value}" STREQUAL "")
    set(_value "${ARG_FALLBACK}")
  endif()
  string(REGEX REPLACE "[^A-Za-z0-9.-]" "." _value "${_value}")
  set("${OUTPUT_VARIABLE}" "${_value}" PARENT_SCOPE)
endfunction()

function(_besa_version_resolve)
  if(NOT DEFINED RELEASE_TYPE)
    set(RELEASE_TYPE dev CACHE STRING "Type of release")
  endif()
  if(NOT DEFINED RELEASE_REVISION)
    set(RELEASE_REVISION 1 CACHE STRING "Revision of prerelease")
  endif()
  if(NOT RELEASE_TYPE MATCHES "^(dev|release|alpha|beta|rc)$")
    _besa_fatal(
      "besa_configure_complete"
      "invalid RELEASE_TYPE '${RELEASE_TYPE}'. Expected dev, release, alpha, beta, or rc"
    )
  endif()

  if(RELEASE_TYPE STREQUAL "release")
    set(_semver "${PROJECT_VERSION}")
  elseif(RELEASE_TYPE STREQUAL "dev")
    _besa_git_value(_branch COMMAND "rev-parse --abbrev-ref HEAD" FALLBACK "nogit")
    _besa_git_value(_hash COMMAND "rev-parse --short HEAD" FALLBACK "nogit")
    set(_semver "dev.${_branch}.${_hash}")
  else()
    set(_semver "${PROJECT_VERSION}-${RELEASE_TYPE}.${RELEASE_REVISION}")
  endif()

  set(PROJECT_SEMVER "${_semver}" CACHE INTERNAL "Resolved project semantic version")
  set(PROJECT_SEMVER "${_semver}" PARENT_SCOPE)

  string(REGEX REPLACE "[^A-Za-z0-9_]" "_" _namespace "${PROJECT_NAME}")
  set(_include_dir "${PROJECT_BINARY_DIR}/generated/include")
  set(_header_dir "${_include_dir}/${PROJECT_NAME}")
  file(MAKE_DIRECTORY "${_header_dir}")
  file(WRITE "${_header_dir}/version.hpp"
    "// Generated by BESA.\n#pragma once\n#include <string_view>\n\n"
    "namespace ${_namespace} {\n"
    "inline constexpr std::string_view version = \"${_semver}\";\n"
    "} // namespace ${_namespace}\n"
  )
  set(BESA_VERSION_INCLUDE_DIR "${_include_dir}" CACHE INTERNAL "BESA generated version include")
  set(BESA_VERSION_INCLUDE_DIR "${_include_dir}" PARENT_SCOPE)
endfunction()
