# --------------------------------------------------------------------------------------------------
# SPDX-FileCopyrightText: 2026 BESA developers
# SPDX-License-Identifier: Apache-2.0
# --------------------------------------------------------------------------------------------------
set(_manifest "${BINARY_DIR}/besa/manifest.json")
if(NOT EXISTS "${_manifest}")
  message(FATAL_ERROR "missing ${_manifest}")
endif()
file(READ "${_manifest}" _json)
string(JSON _project GET "${_json}" project)
string(JSON _count LENGTH "${_json}" units)
if(NOT _project STREQUAL "basic" OR NOT _count EQUAL 2)
  message(FATAL_ERROR "unexpected manifest:\n${_json}")
endif()
string(JSON _type0 GET "${_json}" units 0 type)
string(JSON _type1 GET "${_json}" units 1 type)
if(NOT _type0 STREQUAL "cpp" OR NOT _type1 STREQUAL "bin")
  message(FATAL_ERROR "expected cpp and bin units:\n${_json}")
endif()
string(JSON _language0 GET "${_json}" units 0 language)
string(JSON _parser_language0 GET "${_json}" units 0 parse language)
if(NOT _language0 STREQUAL "cpp" OR NOT _parser_language0 STREQUAL "cpp")
  message(FATAL_ERROR "cpp unit did not preserve semantic/parser language:\n${_json}")
endif()
string(JSON _headers LENGTH "${_json}" units 0 headers)
string(JSON _sources LENGTH "${_json}" units 0 sources)
if(NOT _headers EQUAL 1 OR NOT _sources EQUAL 1)
  message(FATAL_ERROR "cpp unit did not lower to include/lib roots:\n${_json}")
endif()
